markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-theme-cayman
github: [metadata]

show_drafts         : true

collections:
    topics:
        output: true
        permalink: /topics/:path/
        
